[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Accept = "text/html"}

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
